# -*- coding: utf-8 -*-
"""Assignment_1_AcceleratedDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4C2MERi4yBBDW8yWO2k-9Lzhp8tWXws
"""

import numpy as np

# Q1
arr = np.array([1, 2, 3, 6, 4, 5])

# Reversing the array
reversed_arr = arr[::-1]

# Output
print("Original Array:", arr)
print("Reversed Array:", reversed_arr)

# Q2
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

# Given arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

# Element-wise comparison
print("Element-wise Comparison:")
print(arr1 == arr2)

# Complete array comparison
print("Are both arrays exactly equal?")
print(np.array_equal(arr1, arr2))

# Q3
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Finding unique values and their counts
values, counts = np.unique(x, return_counts=True)

# Finding most frequent value
most_frequent = values[np.argmax(counts)]

# Finding indices of the most frequent value
indices = np.where(x == most_frequent)

# Output
print("Array:", x)
print("Most Frequent Value:", most_frequent)
print("Indices of Most Frequent Value:", indices)

# Given array
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Finding unique values and their counts
values, counts = np.unique(y, return_counts=True)

# Finding most frequent value
most_frequent = values[np.argmax(counts)]

# Finding indices
indices = np.where(y == most_frequent)

# Output
print("Array:", y)
print("Most Frequent Value:", most_frequent)
print("Indices of Most Frequent Value:", indices)

#Q4
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# Sum of all elements
total_sum = np.sum(gfg)

print("Matrix:\n", gfg)
print("Sum of all elements:", total_sum)

# Row-wise sum
row_sum = np.sum(gfg, axis=1)

print("Row-wise Sum:")
print(row_sum)

# Column-wise sum
column_sum = np.sum(gfg, axis=0)

print("Column-wise Sum:")
print(column_sum)